# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='mobno',
            field=models.IntegerField(),
        ),
    ]
